### ISSUE TITLE
Enhance new user onboarding experience

### ISSUE THREAD

**Issue by r0adkll** [r0adkll/DeckBox#11]
Add some onboarding elements to improve the first launch experience:

* "Get Started" guided tool tips
* Starter/Example Decks to view and play with
* Deck building tips and guides

My thoughts on this were adding a card on the home screen that presents some sort of first launch introduction followed by some example/starter decks beneath it to get the user started.  

## Tasks
* [x] Remove quick-tip bubble that pops up for new users
* [x] Add QuickStart card to main screen that gives the users a list of deck templates (Tournament winners, Theme Decks, etc) so that they can jump write into deck building
* [x] Remove onboarding flow that the user encounters while opening the app for the first time

**Comment by r0adkll** [comment]
I got consent from limitlesstcg.com to scrape their tournament data to use in an improved onboarding experience.

**Comment by r0adkll** [comment]
Closed as of #48
