### ISSUE TITLE
Full Offline Capability

### ISSUE THREAD

**Issue by r0adkll** [r0adkll/DeckBox#6]
Expand the caching features in the application.

There is already a subsystem in place to download and cache the card data from [pokemontcg.io](https://pokemontcg.io) which you can find here: [DefaultCardManager](https://github.com/r0adkll/DeckBox/blob/development/app/src/main/java/com/r0adkll/deckbuilder/arch/data/features/cards/DefaultCacheManager.kt) and here [CacheService](https://github.com/r0adkll/DeckBox/blob/development/app/src/main/java/com/r0adkll/deckbuilder/arch/data/features/cards/service/CacheService.kt)

This now works when searching for cards, but image cache still needs to be implemented for a truly offline experience. My intention was to leverage [Glide's built in caching mechanism].(https://bumptech.github.io/glide/doc/configuration.html#disk-cache) to cache card images one set at a time (as caching EVERY SINGLE CARD would be too expensive) so that they will automatically work without too much effort

## Tasks

* [x] Replace Requery with Room
* [x] Improve Firestore Deck format to pull from local card cache or network instead of storing card data.
* [x] Create Room Deck entity to enable support for complete offline mode
* [x] Add UI to allow users to cache data/images on a per set basis
* [ ] ~Add improved Cache management UI in the settings~ (_until further notice_)

**Comment by r0adkll** [comment]
Expanding this issue to cover a broader scope. 

The current "anonymous/offline" user implementation needs to be sunsetted to help streamline the onboarding experience for users. Ideally, I would like to remove the Login screen in favor of an offline-first implementation where the user can later link their device to Google account and switch over to using Firestore instead of local SQLite.

In combination with the aforementioned caching feature, this would enable a fully offline experience for users that want it, while maintaining the current online implementation for those that link their Google account.
